### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by abdou31** [vijayg15/FaceMask-Detection#1]
Hello,
Thanks for this project.
Can you please send a link for the dataset used in this repository?

**Comment by vijayg15** [comment]
You can use any available open source dataset for the training purpose.
or you can also create your own dataset too.

**Comment by martingra** [comment]
The dataset of images used and/or the h5 model resulting from training would be very usefull

**Comment by vijayg15** [comment]
Hi
I've already shared the complete methodology.
You just need to download images from internet or you can use some open source dataset available like [this one](https://github.com/X-zhangyang/Real-World-Masked-Face-Dataset) and run the code on your machine!
