### ISSUE TITLE
can you provide the h5 file 

### ISSUE THREAD

**Issue by siddharthakanchar** [vijayg15/FaceMask-Detection#2]
I would be thankful to you if you can provide the data and h5 file

**Comment by vijayg15** [comment]
> I would be thankful to you if you can provide the data and h5 file

Dear @siddharthakanchar 

1. I've collected data from my friends and near one and to share that data I need to take permission from all of them, so sorry for that.
2. I can't share the fine tuned weights but yeah would share the weights that would predict the mask sufficiently.

well, my suggestion is, you should collect your own data(or the available open source like [this one](https://github.com/X-zhangyang/Real-World-Masked-Face-Dataset)) and run the model to get the fine tuned weights.
